# Generated by Django 4.2.14 on 2024-07-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='An easy to make recipe of cookies, crispy on the edges and soft on the inside with chocolate bombs in each bite.'),
            preserve_default=False,
        ),
    ]
